### ISSUE TITLE
Deprecate, move and re-organize FT_v2

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/deprecated__Figuren_Theater__v2#1]
```[tasklist]
### Tasks
- [ ] https://github.com/figuren-theater/ft-data/issues/21
- [ ] https://github.com/figuren-theater/ft-performance/issues/27
- [ ] https://github.com/figuren-theater/ft-core-block-domaincheck/issues/5
- [ ] https://github.com/figuren-theater/deprecated__plugins__v2/issues/1
- [ ] https://github.com/figuren-theater/ft-options/issues/12
- [ ] https://github.com/figuren-theater/ft-seo/issues/15
- [ ] https://github.com/figuren-theater/ft-onboarding/issues/29
```
